###
# Engine
###

#pylint: skip-file

from os.path import join
from glob import glob

Import('env')

modules = [elem for elem in Dir('src').children() if elem.isdir()]



# # Configure 'core.hpp'
# core_header_path = Dir('src/core')
# core_header = core_header_path.glob('*')
# print(dir(core_header[0].attributes))
# # core_header = [str(elem) for elem in core_header]

# with open('include/engine/core.hpp', 'w') as core_hpp:
# 	core_hpp.write('#pragma once\n\n')
# 	for elem in core_header:
# 		core_hpp.write('#include "' + elem + '"\n')

# # Build core
# core_source = glob(pathname='src/core/**/*.cpp', recursive=True)

# core = env.SharedLibrary('./shared/core', core_source, LIBS=['glfw', 'fmt', 'spdlog'])
