###
# Application Layer
###

#pylint: skip-file

from os.path import join

Import('env', 'buildPath', 'libPath')

window = env.SharedLibrary(join(libPath,'window'), ['window.cpp'], LIBS=['glfw'])

Return('window')
