###
# Engine Core
###

#pylint: skip-file

from os.path import join

Import('env', 'buildPath', 'staticPath', 'sharedPath')

engineCore = env.SharedLibrary(join(sharedPath,'engineCore'), [Glob('**/*.cpp')], LIBS=['glfw'])
