### 
# Engine core
###

# pylint: skip-file

Import('env')

buildPath = '#engine/build/'

window = SConscript(
	['application_layer/SConscript'],
	exports=['env', 'buildPath']
)

engine = env.Program(buildPath+'Engine', ['main.cpp'], LIBS=[window])